### PR TITLE
Changed NYTimes to lowercase to fix issues with case sensitive file systems.

### PR DESCRIPTION
**Pull request by lfreijo**
This fixes issues with go mod on case sensitive file systems.

### CODE REVIEW

**Comment by jprobinson** [comment]
Hi @lfreijo! While our organization has switched to `nytimes`, the library was written while we were `NYTimes` so this actually causes a breaking change. To install the library properly with the uppercase directory, we recommend using an uppercase name while fetching it:
```
go get github.com/NYTimes/logrorate
```

I'll look to add an install note in the README similar to the one we have on gizmo: https://github.com/nytimes/gizmo#install, sorry for the confusion!

**Comment by jprobinson** [comment]
FYI, I've added a note here: https://github.com/nytimes/logrotate#install

**Comment by lfreijo** [comment]
Ok. Using the capitalized version in go get does not work for me on Mac OS 10.14.5. I'll just use my fork now.

**Comment by jprobinson** [comment]
I'm using a similar OS version without issues. Your problem now may be due to the library already existing on your GOPATH/build cache or being referenced with the lowercase `nytimes` somewhere else?

**Comment by jprobinson** [comment]
I'm using a similar OS version without issues. Your problem now may be due to the library already existing on your GOPATH/build cache or being referenced with the lowercase `nytimes` somewhere else?

**Comment by fsouza** [comment]
@lfreijo does the folder ``$GOPATH/src/github.com/nytimes`` exist? If so, can you get rid of it and try again?

**Pull request closed without merging**
